let inventory = [
  {
    id: '0',
    name: 'Believer',
    artist: 'Imagine Dragons',
    album: 'Evolve',
    year: '2017',
    song: 'songs/Believer.mp3',
    image: 'img/evolve.jpg',
    wav: '',
    ogg: '',
  },
  {
    id: '1',
    name: 'Friends',
    artist: 'Marshmello ft Anne Marie',
    album: 'Speak Your Mind',
    year: '2018',
    song: 'songs/Friends.mp3',
    image: 'img/speakyourmind.jpg',
    wav: '',
    ogg: '',
  },
  {
    id: '2',
    name: 'When The Party*s Over',
    artist: 'Billie Eilish',
    album: 'When We All Fall Asleep, Where Do We Go?',
    year: '2018yon',
    song: 'songs/When the partys over.mp3',
    image: 'img/whenthepartysover.jpg',
    wav: '',
    ogg: '',
  },
  {
    id: '3',
    name: 'Youngblood',
    artist: '5 Seconds of Summer',
    album: 'Youngblood',
    year: '2018',
    song: 'songs/Youngblood.mp3',
    image: 'img/youngblood.jpg',
    wav: '',
    ogg: '',
  },
];
